# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Slack messaging Dienst'
        en: 'Slack messaging service'
    maintainer: rthill
#    tester:                        # Who tests this plugin?
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                # Plugin version
    sh_minversion: 1.1            # minimum shNG version to use this plugin
#    sh_maxversion:               # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False         # plugin supports multi instance
    classname: Slack              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    slack:
        class_name: Slack
        class_path: plugins.slack
        token: abc/123/xyz
item_attributes:
    # Definition of item attributes defined by this plugin